"""Tables for the game engine port (original CannonBall engine, src/o*.s).

build/gen/gametab.s / .inc:
  ZoomLookup   Rev B ROM zoom table (with CannonBall corrections): per zoom
               index 0-255: hw zoom, width/height lookup mask, size offset
               (3 words, little endian)
  TrkSections  trackloader: per section (15 levels in STAGE_ORDER, split, 5
               ends): rom0 addresses of the curve, width/height and scenery
               tables (3 longs, little endian words: lo, hi)
  StageData    STAGE_MAPPING_USA (40 bytes: stage lookup offset -> level id)
"""
import os
import re
import struct
import sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from orroms import Roms, zoom_lookup

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GEN = os.path.join(ROOT, "build", "gen")

def main():
    z = zoom_lookup()
    assert len(z) == 256 * 4, len(z)
    asm = ["; generated by tools/mkgame.py", ".p816", '.segment "BANK37"', ".export ZoomLookup", "ZoomLookup:"]
    for i in range(256):
        asm.append("    .word $%04X, $%04X, $%04X   ; %d" % (z[i * 4], z[i * 4 + 1], z[i * 4 + 2], i))
    R = Roms()
    r32 = lambda a: R.r32(R.rom0, a)
    stage_map = [0x3C, 0, 0, 0, 0, 0, 0, 0, 0x1E, 0x3B, 0, 0, 0, 0, 0, 0, 0x20, 0x2F, 0x2A, 0, 0, 0, 0, 0,
                 0x2D, 0x35, 0x33, 0x21, 0, 0, 0, 0, 0x32, 0x23, 0x38, 0x22, 0x26, 0, 0, 0]
    order = [0, 8, 9, 16, 17, 18, 24, 25, 26, 27, 32, 33, 34, 35, 36]
    secs = []
    for o in order:                         # setup_level: +24 curve, +28 wh, +32 scenery
        adr = r32(0xE528 + (stage_map[o] << 2))
        secs.append((r32(adr + 24), r32(adr + 28), r32(adr + 32)))
    adr = 0x1DFA4                           # setup_section: +0 curve, +4 wh, +8 scenery
    secs.append((r32(adr), r32(adr + 4), r32(adr + 8)))
    for i in range(5):
        adr = r32(0xE514 + i * 4)
        secs.append((r32(adr), r32(adr + 4), r32(adr + 8)))
    asm += [".export TrkSections, StageData", "TrkSections:"]
    for c, w, sc in secs:
        asm.append("    .word $%04X, $%04X, $%04X, $%04X, $%04X, $%04X" % (c & 0xFFFF, c >> 16, w & 0xFFFF, w >> 16, sc & 0xFFFF, sc >> 16))
    asm += ["StageData:", "    .byte " + ", ".join("$%02X" % v for v in stage_map)]
    open(os.path.join(GEN, "gametab.s"), "w").write("\n".join(asm) + "\n")
    open(os.path.join(GEN, "gametab.inc"), "w").write("; generated by tools/mkgame.py\n.global ZoomLookup, TrkSections, StageData\nTRK_SPLIT = 15\nTRK_END0 = 16\n")
    print("zoom lookup: 256 entries")


if __name__ == "__main__":
    main()
