#!/usr/bin/env python3
"""[W1c] Data of the overhead structures shown on BG1 / BG2 (src/ohb.inc).

K1 texture sets: wide overhead strips made of one repeating texture are
drawn as rows of a texture cut from their largest frame at the SNES 1:1
scale (horizontal 0.8); the backend picks one texture row per screen line
(the strip's exact height), so the texture is not scaled horizontally.
  set 0, the Gateway arches' beams (frame descriptors 422-426, two mirrored
    halves per arch): descriptor 422 (192 x 47 px), columns 40.. (15 tiles:
    no rounded end, the stone joints every ~30 px), rows 0..43; the bottom
    rows 44..46 hold coloured keystones near the middle of the arch, so they
    come from the plain underside (columns 10..77, repeated); 6 tile rows.
  set 1, the cloud ceiling of the cloudy mountain course (descriptors
    1065-1073, one strip at different depths): descriptor 1065 (199 x 31
    px, periodic every 48 px): columns 8..55 (6 tiles), 4 tile rows.  The
    smaller frames 1066-1073 are shrunk copies of it (31 to 1 rows, opaque
    but for their edge rows): the rows are sampled centred (flag bit 0: the
    one row of 1073 is the strip's middle, not its transparent top edge).
    The strips overlap (the nearer one in front, lower on screen the
    farther ones): the gaps of a strip's bottom rows show the strip behind
    in the arcade, a BG line shows one strip: they take the colour above.

Colours: the arcade colour indices a texture uses go to BG palette 6,
colours 1-7 and 12-15 (8-11 are the road's).

Output: build/gen/ohbdat.s / ohbdat.inc (ROM-derived: stays local).
"""
import os
import sys
import numpy as np
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from orroms import Roms
import mksprv3

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GEN = os.path.join(ROOT, 'build', 'gen')
SLOTS = [1, 2, 3, 4, 5, 6, 7, 12, 13, 14, 15]   # BG palette 6 colours free of the road
SEG = 'BANK0F'
D0 = 0xF236                     # first frame descriptor (rom0)


def beam(F):
    a = F.render(422, 0x200, 0)             # 47 x 192
    assert a.shape[0] == 47
    tw, th = 15, 6
    tex = np.zeros((th * 8, tw * 8), dtype=np.uint8)
    tex[:44] = a[:44, 40:40 + tw * 8]
    under = a[44:47, 10:78]
    for x in range(tw * 8):
        tex[44:47, x] = under[:, x % under.shape[1]]
    return dict(lo=422, hi=427, tex=tex, tw=tw, th=th, rows=47, flags=0)


def clouds(F):
    a = F.render(1065, 0x200, 0)            # 31 x 199, period 48 px
    assert a.shape[0] == 31
    tw, th = 6, 4
    tex = np.zeros((th * 8, tw * 8), dtype=np.uint8)
    tex[:31] = a[:31, 8:8 + tw * 8]
    for y in range(16, 31):
        for x in range(tw * 8):
            if tex[y, x] == 0:
                tex[y, x] = tex[y - 1, x]
    return dict(lo=1065, hi=1074, tex=tex, tw=tw, th=th, rows=31, flags=1)


def main():
    R = Roms()
    F = mksprv3.Frames(R)
    sets = [beam(F), clouds(F)]
    asm = ['; generated by tools/mkohb.py (ROM-derived: stays local)', '.p816',
           '.segment "%s"' % SEG, '.export OhbSets']
    tab = []
    tmax = 0
    for k, st in enumerate(sets):
        tex = st['tex']
        cols = sorted(set(int(c) for c in np.unique(tex)) - {0})
        if len(cols) > len(SLOTS):
            raise SystemExit('texture %d colours %s do not fit %d slots' % (k, cols, len(SLOTS)))
        cmap = {c: SLOTS[i] for i, c in enumerate(cols)}
        t2 = np.zeros_like(tex)
        for c, sl in cmap.items():
            t2[tex == c] = sl
        blocks = [t2[r * 8:r * 8 + 8, c * 8:c * 8 + 8] for r in range(st['th']) for c in range(st['tw'])]
        data = mksprv3.tiles4(blocks)
        open(os.path.join(GEN, 'ohbtex%d.bin' % k), 'wb').write(data)
        slotc = [0] * 16
        for c, sl in cmap.items():
            slotc[sl] = c
        n = st['tw'] * st['th']
        tmax = max(tmax, n)
        asm += ['OhbTex%d: .incbin "ohbtex%d.bin"   ; set %d tiles (%d x %d, row-major, 4bpp)' % (k, k, k, st['th'], st['tw']),
                'OhbCol%d: .byte %s  ; per BG colour 0-15: arcade colour (0 none)' % (k, ', '.join(str(v) for v in slotc))]
        tab.append(st)
        print('ohb set %d: frames %d-%d, texture %d x %d tiles, %d rows, colours %s -> slots %s'
              % (k, st['lo'], st['hi'] - 1, st['tw'], st['th'], st['rows'], cols, [cmap[c] for c in cols]))
    # OhbSets: per set 16 bytes: descriptor range (rom0 addresses, low words; bank bits
    # 16-17), tiles address, tile count, TW, TH, source rows, colour map address
    asm += ['; OhbSets (16 bytes a set): +0 first / +2 end frame descriptor address (bits 0-15),',
            '; +4 their bits 16-17, +5 tiles bank, +6 tiles address, +8 tiles, +10 TW, +11 TH,',
            '; +12 source rows, +13 flags (bit 0: centred row sampling), +14 colour map',
            '; address (same bank)',
            'OhbSets:']
    for k, st in enumerate(tab):
        lo, hi = D0 + st['lo'] * 10, D0 + st['hi'] * 10
        assert lo >> 16 == (hi - 1) >> 16
        asm.append('    .word $%04X, $%04X' % (lo & 0xFFFF, hi & 0xFFFF))
        asm.append('    .byte %d, ^OhbTex%d' % (lo >> 16, k))
        asm.append('    .word .loword(OhbTex%d), %d' % (k, st['tw'] * st['th']))
        asm.append('    .byte %d, %d' % (st['tw'], st['th']))
        asm.append('    .byte %d, %d' % (st['rows'], st['flags']))
        asm.append('    .word .loword(OhbCol%d)' % k)
    open(os.path.join(GEN, 'ohbdat.s'), 'w').write('\n'.join(asm) + '\n')
    inc = ['; generated by tools/mkohb.py',
           'OHB_NSETS = %d           ; K1 texture sets (OhbSets)' % len(tab)]
    for k, st in enumerate(tab):
        inc.append('OHB_S%dLO = $%04X         ; set %d: descriptor addresses (bits 0-15) [lo, hi)'
                   % (k, (D0 + st['lo'] * 10) & 0xFFFF, k))
        inc.append('OHB_S%dHI = $%04X' % (k, (D0 + st['hi'] * 10) & 0xFFFF))
    inc += [
           'OHB_TNMAX = %d          ; tiles of a set at most' % tmax,
           'OHB_THMAX = %d           ; tile rows of a set at most' % max(st['th'] for st in tab),
           '.global OhbSets']
    open(os.path.join(GEN, 'ohbdat.inc'), 'w').write('\n'.join(inc) + '\n')


if __name__ == '__main__':
    main()
