"""Arcade main CPU ROM (rom0, 256 KB) for the ported game code.

Placed at ROM file offset $110000 (LoROM banks $22-$29), 64 KB aligned: the
SA-1 HiROM view (DXB = 1: banks $D0-$DF = file $100000-$1FFFFF) shows it
linearly, so arcade rom0 address A is at $D1 + (A >> 16) : (A & $FFFF)
(big endian, as the 68000 reads it). See src/arcrom.inc.
"""
import os
from orroms import Roms

GEN = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "build", "gen")
FIRST_BANK = 0x22

def main():
    R = Roms()
    asm = ["; generated by tools/mkrom0.py", ".p816"]
    for b in range(8):
        fn = "rom0_%d.bin" % b
        open(os.path.join(GEN, fn), "wb").write(bytes(R.rom0[b * 0x8000:(b + 1) * 0x8000]))
        asm += ['.segment "BANK%02X"' % (FIRST_BANK + b), 'ArcRom0_%d: .incbin "%s"' % (b, fn)]
    open(os.path.join(GEN, "rom0.s"), "w").write("\n".join(asm) + "\n")
    print("rom0: banks $%02X-$%02X" % (FIRST_BANK, FIRST_BANK + 7))

if __name__ == "__main__":
    main()
