#!/usr/bin/env python3
"""Intern exact road-X write results into small, collision-free ROM keys.

Each key describes all writes made by SetupXData, including its marker
prefix and untouched entries. Equal consecutive keys can reuse RD_X even
when the underlying path vectors differ. Unknown positions keep the normal
runtime calculation. No projected coordinates or pixels are approximated.
"""
from pathlib import Path
import math
import re
import struct

ROOT = Path(__file__).resolve().parent.parent
GEN = ROOT / "build" / "gen"
BANKS = (0x1D, 0x30, 0x31)


def s16(v):
    return (v + 0x8000) % 0x10000 - 0x8000


def s32(v):
    return (v + 0x80000000) % 0x100000000 - 0x80000000


def trunc_div(a, b):
    if b == 0:
        return 0
    return (abs(a) // abs(b)) * (1 if (a >= 0) == (b >= 0) else -1)


def projection(words, pos):
    """SetupXData writes; -32768 denotes an entry that is left untouched."""
    p = pos * 2
    x, y = s16(words[p] + words[p + 2]), s16(words[p + 1] + words[p + 3])
    distance = math.isqrt(x*x + y*y)
    dx, dy = s16(trunc_div(x << 14, distance)), s16(trunc_div(y << 14, distance))
    xt = yt = old_end = old_inc = 0
    scan = 447
    output = [-32768] * 448
    for sample in range(33):
        q = p + sample * 4
        xt = s32(xt + s16(words[q] + words[q + 2]))
        yt = s32(yt + s16(words[q + 1] + words[q + 3]))
        tx, ty = s16(xt >> 5), s16(yt >> 5)
        cross = s32(tx * dy - ty * dx)
        dot = s32(tx * dx + ty * dy) >> 7
        divisor = s16((dot >> 7) + 0x410)
        inc, end = s16(trunc_div(cross, divisor)), s16(trunc_div(dot, divisor) * 4)
        steps = s16(end - old_end)
        if steps < 0:
            break
        if steps == 0:
            continue
        delta, value = s16(trunc_div(inc - old_inc, steps)), old_inc
        for _ in range(steps + 1):
            value = s16(value + delta)
            if not -0x3200 <= value <= 0x3200:
                break
            output[scan] = value
            scan -= 1
            if scan < 0:
                break
        else:
            old_inc, old_end = inc, end
            continue
        break
    for i in range(min(scan, 127) + 1):
        output[i] = 0x3210
    return struct.pack("<448h", *output)


def generate():
    source = (GEN / "road2.s").read_text()
    sections = re.findall(r"\.faraddr RawPath_([0-9A-F]+)", source)
    names = list(dict.fromkeys(sections))
    intern, table_labels = {}, {}
    lines = ['; generated by tools/mkroadkeys.py', '.p816']
    bank_index = used = total = old_hits = new_hits = 0
    for name in names:
        raw = (GEN / f"road2_path_{name}.bin").read_bytes()
        words = struct.unpack(f"<{len(raw)//2}h", raw)
        count = len(words)//2 - 65
        keys = []
        previous_raw = previous_key = None
        for pos in range(count):
            current_raw = raw[pos*4:pos*4+264]
            if current_raw == previous_raw:
                key = previous_key
                old_hits += 1
            else:
                result = projection(words, pos)
                key = intern.setdefault(result, len(intern))
            new_hits += key == previous_key
            keys.append(key)
            previous_raw, previous_key = current_raw, key
        assert len(intern) < 0xFFFF, "road keys need more than 16 bits"
        if used + count*2 > 0x8000:
            bank_index += 1
            used = 0
        assert bank_index < len(BANKS), "road keys exceed reserved banks"
        label = "RoadKeys_" + name
        lines += [f'.segment "BANK{BANKS[bank_index]:02X}"', label + ':']
        for i in range(0, count, 16):
            lines.append('    .word ' + ','.join(str(v) for v in keys[i:i+16]))
        used += count*2
        total += count
        table_labels[name] = (label, count)
    lines += ['.segment "RODATA"', '.export RoadKeySections', 'RoadKeySections:']
    for name in sections:
        label, count = table_labels[name]
        lines += [f'    .faraddr {label}', f'    .word {count}']
    (GEN / "roadkeys.s").write_text('\n'.join(lines) + '\n')
    print(f"road keys: {total} positions, {len(intern)} exact results, {total*2+len(sections)*5} bytes")
    print(f"consecutive reusable positions: raw inputs {old_hits}, exact outputs {new_hits}")


if __name__ == '__main__':
    generate()
