"""Convert OutRun track data into SNES tables (build/gen/roaddata.s / .inc).

Per section (15 stages + split + 5 end sections): the arcade width/height and
curve tables (big endian, read with XBA), SectionTab pointers; shared: the
height map (rom1 region, big endian) + pointer table, level palettes.
(Road paths: tools/mkroad2.py.)
"""
import math
import os
import numpy as np
from orroms import Roms, pal_to_bgr15
from roadsim import (Track, STAGE_MAPPING_USA, STAGE_ORDER, ROAD_HEIGHT_LOOKUP,
                     ROAD_BGCOLOR, PAL_SKY_TABLE, PAL_GND_TABLE, s16, cdiv)

GEN = os.path.join(os.path.dirname(__file__), "..", "build", "gen")
os.makedirs(GEN, exist_ok=True)
R = Roms()
T = Track(R)
NPOS = 0x904 + 80
LSCALE = 80
FSH = 8
NFTAB = 5000
BANK0 = 0x20            # height / width / curve tables


def path_table(addr):
    out = bytearray()
    for p in range(NPOS):
        a = addr + p * 4
        x0 = R.s16(R.rom1, a); y0 = R.s16(R.rom1, a + 2)
        x1 = R.s16(R.rom1, a + 4); y1 = R.s16(R.rom1, a + 6)
        sx = s16(x0 + x1); sy = s16(y0 + y1)
        dist = math.isqrt(sx * sx + sy * sy) & 0xFFFF
        if dist == 0:
            cxd = cyd = 0
        else:
            cxd = s16(cdiv(sx << 14, dist))
            cyd = s16(cdiv(sy << 14, dist))
        # tilemap h target (set_tilemap_x) from 4 vectors starting at p
        x = s16(sum(R.s16(R.rom1, a + k * 4) for k in range(4)))
        y = s16(sum(R.s16(R.rom1, a + k * 4 + 2) for k in range(4)))
        xa, ya = abs(x), abs(y)
        if ya > xa:
            sc = cdiv(0x100 * x, y)
        else:
            sc = cdiv(-0x100 * y, x) if x else 0
        if x > 0:
            sc += 0x200
        elif x < 0:
            sc += 0x600
        elif y >= 0:
            sc += 0x200
        else:
            sc += 0x600
        if ya > xa:
            sc += -0x200 if x * y >= 0 else 0x200
        # polar form of the (sx,sy) pair: 10-bit angle, 8-bit length (units of LSCALE)
        ang = int(round(math.atan2(sy, sx) / (2 * math.pi) * 1024)) & 1023
        ln = min(255, int(round(math.hypot(sx, sy) / LSCALE)))
        out += ang.to_bytes(2, "little")
        out += bytes([ln, 0])
        out += (s16(sc) & 0xFFFF).to_bytes(2, "little")
        out += b"\x00\x00"
    return out


def copy_table(rom, addr, size):
    return bytes(rom[addr:addr + size])


def wh_size(addr):
    n = 0
    while R.r16(R.rom0, addr + n * 8) < 0x7FFF:
        n += 1
    return (n + 1) * 8


def curve_size(addr):
    n = 0
    while R.r16(R.rom0, addr + n * 6) != 0xFFFF:
        n += 1
    return (n + 1) * 6


def main():
    sections = []
    for i, L in enumerate(T.levels):
        sections.append(("L%d" % i, L, True))
    sections.append(("SPLIT", T.split, False))
    for i, L in enumerate(T.ends):
        sections.append(("END%d" % i, L, False))

    asm = ["; generated by tools/mkroaddata.py", ".p816", ""]
    inc = ["; generated by tools/mkroaddata.py"]
    chunks = []
    # height map region (rom1, big endian) + 24-bit pointer table
    hptrs = [R.r32(R.rom1, ROAD_HEIGHT_LOOKUP + n * 4) for n in range(218)]
    hlo = min(hptrs)
    hhi = max(hptrs) + 0x200
    chunks.append(("HeightData", bytes(R.rom1[hlo:hhi])))
    # width/height & curve tables per section (big endian, read with XBA)
    for name, L, _ in sections:
        chunks.append(("WH_%s" % name, copy_table(R.rom0, L.width_height, wh_size(L.width_height))))
        chunks.append(("Curve_%s" % name, copy_table(R.rom0, L.curve, curve_size(L.curve))))
    banks = {}
    b = BANK0
    used = 0
    for lbl, data in chunks:
        if len(data) > 0x8000:
            raise SystemExit("chunk too big %s" % lbl)
        if used + len(data) > 0x8000:
            b += 1
            used = 0
        banks.setdefault(b, []).append((lbl, data))
        used += len(data)
    for bnk in sorted(banks):
        asm.append('.segment "BANK%02X"' % bnk)
        for lbl, data in banks[bnk]:
            fn = "rd_%s.bin" % lbl
            open(os.path.join(GEN, fn), "wb").write(data)
            asm.append(".export %s" % lbl)
            asm.append("%s: .incbin \"%s\"" % (lbl, fn))
            inc.append(".global %s" % lbl)
    asm.append("")
    last_bank = max(banks)
    asm.append('.segment "BANK%02X"' % (last_bank + 1))
    asm.append(".export HeightPtrs")
    asm.append("HeightPtrs:")
    for p in hptrs:
        asm.append("    .faraddr HeightData + $%04X" % (p - hlo))
    inc.append(".global HeightPtrs")
    # section descriptor table: (unused 3 bytes) wh(3) curve(3) = 9 bytes
    asm.append(".export SectionTab")
    asm.append("SectionTab:")
    for name, L, _ in sections:
        asm.append("    .faraddr 0, WH_%s, Curve_%s   ; %s" % (name, name, name))
    inc.append(".global SectionTab")
    inc.append("SECTION_SIZE = 9")
    inc.append("SECTION_SPLIT = 15")
    inc.append("SECTION_END0 = 16")
    # level palettes: sky(64) ground(16) road(16) -> 96 words = 192 bytes per level
    asm.append(".export LevelPals")
    asm.append("LevelPals:")
    for i, L in enumerate(T.levels):
        s = R.r32(R.rom0, PAL_SKY_TABLE + L.pal_sky * 4)
        sky = [pal_to_bgr15(R.r16(R.rom0, s + k * 2)) for k in range(64)]
        g = R.r32(R.rom0, PAL_GND_TABLE + L.pal_gnd * 4)
        gnd = [pal_to_bgr15(R.r16(R.rom0, g + k * 2)) for k in range(16)]
        road = []
        for pr in (0, 1):
            for v in (L.road[pr], L.stripe[pr], L.side[pr], L.stripe_centre[pr]):
                road.append(pal_to_bgr15((v >> 16) & 0xFFFF))
                road.append(pal_to_bgr15(v & 0xFFFF))
        words = sky + gnd + road
        asm.append("    ; level %d" % i)
        for k in range(0, len(words), 16):
            asm.append("    .word " + ", ".join("$%04X" % w for w in words[k:k + 16]))
    # the same in arcade palette format (opalette port): sky 64, ground 16,
    # road 1 (entries $400-$407), road 2 ($408-$40F) words = 192 bytes
    asm.append(".export ArcLevelPals")
    asm.append("ArcLevelPals:")
    for i, L in enumerate(T.levels):
        s = R.r32(R.rom0, PAL_SKY_TABLE + L.pal_sky * 4)
        words = [R.r16(R.rom0, s + k * 2) for k in range(64)]
        g = R.r32(R.rom0, PAL_GND_TABLE + L.pal_gnd * 4)
        words += [R.r16(R.rom0, g + k * 2) for k in range(16)]
        for pr in (0, 1):
            for v in (L.road[pr], L.stripe[pr], L.side[pr], L.stripe_centre[pr]):
                words += [(v >> 16) & 0xFFFF, v & 0xFFFF]
        asm.append("    ; level %d" % i)
        for k in range(0, len(words), 16):
            asm.append("    .word " + ", ".join("$%04X" % w for w in words[k:k + 16]))
    inc.append(".global ArcLevelPals")
    inc.append("ARCPAL_SKY = 0")
    inc.append("ARCPAL_GND = 128")
    inc.append("ARCPAL_ROAD = 160")
    inc.append(".global LevelPals")
    inc.append("LEVELPAL_SIZE = 192")
    inc.append("LEVELPAL_SKY = 0")
    inc.append("LEVELPAL_GND = 128")
    inc.append("LEVELPAL_ROAD = 160")
    open(os.path.join(GEN, "roaddata.s"), "w").write("\n".join(asm) + "\n")
    open(os.path.join(GEN, "roaddata.inc"), "w").write("\n".join(inc) + "\n")
    print("road data banks $%02X-$%02X" % (BANK0, last_bank + 1))

if __name__ == "__main__":
    main()
