#!/usr/bin/env python3
"""Generate console decoration spacing from the original type dimensions.

This policy is independent of render frame rate. Runtime also filters by the
source routine, preserving continuous terrain, clouds and gameplay triggers.
Run after changing the type tables; --check verifies the locally generated policy.
"""
import argparse
from pathlib import Path
from orroms import Roms
from sprites import frame_lods
from mksprv3 import LANDMARK, PEOPLE


def generate():
    rom = Roms()
    gaps = [0] * 256
    for t in range(0x96):
        addr = rom.r32(rom.rom0, 0x11ED2 + t * 4)
        desc = (addr - 0xF236) // 10
        # Goal supports and arch parts are structural, even without a landmark
        # descriptor. The separate KeepArch policy handles complete arches.
        if desc in LANDMARK | PEOPLE or t in (0x19, 0x2f, 0x30):
            continue
        frame = frame_lods(rom, addr)[0]
        area = frame['w'] * frame['h']
        gaps[t] = 40 if area >= 16000 else 32 if area >= 8000 else 24 if area >= 3000 else 16
    gaps[0x34] = 48  # grandstands: repeated crowd + supports are one object
    lines = ['; Generated by tools/mkscenspacing.py; minimum road units per type/side.',
             '; Zero preserves the source pattern. Routine filtering is in scenbudget.s.',
             'SceneSpacing:']
    for start in range(0, 256, 16):
        lines.append('    .word ' + ','.join(str(n) for n in gaps[start:start+16]) + f' ; ${start:02X}-${start+15:02X}')
    return '\n'.join(lines) + '\n'


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    path = Path(__file__).resolve().parents[1] / 'build/gen/scenspacing.inc'
    result = generate()
    if args.check:
        assert path.read_text() == result, 'regenerate build/gen/scenspacing.inc'
    else:
        path.write_text(result)
