#!/usr/bin/env python3
"""Precompute the renderer's exact 65816 sprite-size arithmetic.

Identical source dimensions share 128-word zoom tables. The output lives
in fixed bank CF, independent of the S-CPU's switched sprite-pixel bank.
Inputs are existing generated metadata; no image pixels are changed.
"""
from pathlib import Path
import re
import struct

ROOT = Path(__file__).resolve().parent.parent
GEN = ROOT / "build" / "gen"


def generate():
    meta = (GEN / "sprmeta.bin").read_bytes()
    zoom = (GEN / "sprzt.bin").read_bytes()
    count = int(re.search(r"SPR_DN = (\d+)", (GEN / "sprdat3.inc").read_text())[1])
    dims = [struct.unpack_from("<HH", meta, struct.unpack_from("<H", meta, i * 10)[0] - 0x8000)
            for i in range(count)]
    factors = [struct.unpack_from("<128H", zoom, off) for off in (0x400, 0x500)]
    tables, offsets, indexes = [], {}, []
    for axis, shift in enumerate((6, 5)):
        present = {d[axis] for d in dims}
        index = []
        for size in range(max(present) + 1):
            if size not in present:
                index.append(None)
                continue
            # MR+1 is a 16-bit read; ADC and shifts also operate in 16 bits.
            values = tuple(((((size * factor) >> 8) + (1 << shift) - 1) & 0xFFFF) >> shift
                           for factor in factors[axis])
            if values not in offsets:
                offsets[values] = len(tables) * 256
                tables.append(values)
            index.append(offsets[values])
        indexes.append(index)
    lines = ['; generated by tools/mksprgeom.py', '.p816', '.segment "SA1CODE2"',
             '.export SprWidthOfs, SprHeightOfs, SprSizes']
    for name, index in zip(("SprWidthOfs", "SprHeightOfs"), indexes):
        lines.append(name + ":")
        for off in index:
            lines.append("    .word " + ("$FFFF" if off is None else f".loword(SprSizes + {off})"))
    lines.append("SprSizes:")
    for table in tables:
        for start in range(0, 128, 16):
            lines.append("    .word " + ",".join(str(v) for v in table[start:start + 16]))
    lines.append('.assert * <= $10000, lderror, "sprite geometry exceeds fixed bank CF"')
    (GEN / "sprgeom.s").write_text("\n".join(lines) + "\n")
    print(f"sprite geometry: {len(tables)} shared tables, {len(tables)*256 + sum(map(len, indexes))*2} bytes")


if __name__ == "__main__":
    generate()
