; generated by tools/farbank.py: jsl/rtl trampolines between the SA-1 code banks

.ifdef NEWGAME
.p816
.a16
.i16
.import BcdAdd, ClearPaletteData, DisableSprites, DoSprOrderShadows, FillTilemapColor, HudBlitText1, HudBlitText2, HudDrawScore, HudDrawScoreTile, HudDrawTimer2, HudSetupMiniMap, InHasPressed, InputsWheelRead, MapPalette, OutrunInitBestOutrunners, R0Byte, R0Long, R0Set, R0Word, Random, SDiv16u, SDiv32_16, SMul16, SetTileScroll, SndQueueSound, TrafficDisable, VidClearTextRam, VidReadText8, VidReadTile8, VidSetEnabled, VidWritePal32, VidWriteText16, VidWriteText32, VidWriteText8, VidWriteTile16, VidWriteTile32, VidWriteTile8
.export FC_BcdAdd, FC_ClearPaletteData, FC_DisableSprites, FC_DoSprOrderShadows, FC_FillTilemapColor, FC_HudBlitText1, FC_HudBlitText2, FC_HudDrawScore, FC_HudDrawScoreTile, FC_HudDrawTimer2, FC_HudSetupMiniMap, FC_InHasPressed, FC_InputsWheelRead, FC_MapPalette, FC_OutrunInitBestOutrunners, FC_R0Byte, FC_R0Long, FC_R0Set, FC_R0Word, FC_Random, FC_SDiv16u, FC_SDiv32_16, FC_SMul16, FC_SetTileScroll, FC_SndQueueSound, FC_TrafficDisable, FC_VidClearTextRam, FC_VidReadText8, FC_VidReadTile8, FC_VidSetEnabled, FC_VidWritePal32, FC_VidWriteText16, FC_VidWriteText32, FC_VidWriteText8, FC_VidWriteTile16, FC_VidWriteTile32, FC_VidWriteTile8
.segment "SA1CODE"
FC_BcdAdd:
    jsr BcdAdd
    rtl
FC_ClearPaletteData:
    jsr ClearPaletteData
    rtl
FC_DisableSprites:
    jsr DisableSprites
    rtl
FC_DoSprOrderShadows:
    jsr DoSprOrderShadows
    rtl
FC_FillTilemapColor:
    jsr FillTilemapColor
    rtl
FC_HudBlitText1:
    jsr HudBlitText1
    rtl
FC_HudBlitText2:
    jsr HudBlitText2
    rtl
FC_HudDrawScore:
    jsr HudDrawScore
    rtl
FC_HudDrawScoreTile:
    jsr HudDrawScoreTile
    rtl
FC_HudDrawTimer2:
    jsr HudDrawTimer2
    rtl
FC_HudSetupMiniMap:
    jsr HudSetupMiniMap
    rtl
FC_InHasPressed:
    jsr InHasPressed
    rtl
FC_InputsWheelRead:
    jsr InputsWheelRead
    rtl
FC_MapPalette:
    jsr MapPalette
    rtl
FC_OutrunInitBestOutrunners:
    jsr OutrunInitBestOutrunners
    rtl
FC_R0Byte:
    jsr R0Byte
    rtl
FC_R0Long:
    jsr R0Long
    rtl
FC_R0Set:
    jsr R0Set
    rtl
FC_R0Word:
    jsr R0Word
    rtl
FC_Random:
    jsr Random
    rtl
FC_SDiv16u:
    jsr SDiv16u
    rtl
FC_SDiv32_16:
    jsr SDiv32_16
    rtl
FC_SMul16:
    jsr SMul16
    rtl
FC_SetTileScroll:
    jsr SetTileScroll
    rtl
FC_SndQueueSound:
    jsr SndQueueSound
    rtl
FC_TrafficDisable:
    jsr TrafficDisable
    rtl
FC_VidClearTextRam:
    jsr VidClearTextRam
    rtl
FC_VidReadText8:
    jsr VidReadText8
    rtl
FC_VidReadTile8:
    jsr VidReadTile8
    rtl
FC_VidSetEnabled:
    jsr VidSetEnabled
    rtl
FC_VidWritePal32:
    jsr VidWritePal32
    rtl
FC_VidWriteText16:
    jsr VidWriteText16
    rtl
FC_VidWriteText32:
    jsr VidWriteText32
    rtl
FC_VidWriteText8:
    jsr VidWriteText8
    rtl
FC_VidWriteTile16:
    jsr VidWriteTile16
    rtl
FC_VidWriteTile32:
    jsr VidWriteTile32
    rtl
FC_VidWriteTile8:
    jsr VidWriteTile8
    rtl
.endif
