; generated by tools/farbank.py: jsl/rtl trampolines between the SA-1 code banks

.ifdef NEWGAME
.p816
.a16
.i16
.import HiDisplayScores, HiInit, HiInitDefScores, HiSetupPalBest, HiSetupRoadBest, HiTick, LogoDisable, LogoEnable, LogoTick, MapInit, MapTick, MusicCheckStart, MusicDisable, MusicEnable, MusicPlayMusic, MusicTick
.export TC_HiDisplayScores, TC_HiInit, TC_HiInitDefScores, TC_HiSetupPalBest, TC_HiSetupRoadBest, TC_HiTick, TC_LogoDisable, TC_LogoEnable, TC_LogoTick, TC_MapInit, TC_MapTick, TC_MusicCheckStart, TC_MusicDisable, TC_MusicEnable, TC_MusicPlayMusic, TC_MusicTick
.segment "SA1CODE2"
TC_HiDisplayScores:
    jsr HiDisplayScores
    rtl
TC_HiInit:
    jsr HiInit
    rtl
TC_HiInitDefScores:
    jsr HiInitDefScores
    rtl
TC_HiSetupPalBest:
    jsr HiSetupPalBest
    rtl
TC_HiSetupRoadBest:
    jsr HiSetupRoadBest
    rtl
TC_HiTick:
    jsr HiTick
    rtl
TC_LogoDisable:
    jsr LogoDisable
    rtl
TC_LogoEnable:
    jsr LogoEnable
    rtl
TC_LogoTick:
    jsr LogoTick
    rtl
TC_MapInit:
    jsr MapInit
    rtl
TC_MapTick:
    jsr MapTick
    rtl
TC_MusicCheckStart:
    jsr MusicCheckStart
    rtl
TC_MusicDisable:
    jsr MusicDisable
    rtl
TC_MusicEnable:
    jsr MusicEnable
    rtl
TC_MusicPlayMusic:
    jsr MusicPlayMusic
    rtl
TC_MusicTick:
    jsr MusicTick
    rtl
.endif
